packages:
  - apps/**/*
  - libs/*
  - packages/*
catalogs:
  dev:
    '@antfu/nip': ^0.1.0
    '@iconify-json/circle-flags': ^1.2.6
    '@types/he': ^1.2.3
    '@types/lodash-es': ^4.17.12
    '@types/node': ^22.15.21
    '@types/pg': ^8.15.4
    '@types/progress-stream': ^2.0.5
    '@types/xml2js': ^0.4.14
    '@unocss/preset-icons': ^66.1.2
    domhandler: ^5.0.3
    drizzle-kit: ^0.31.1
    tsup: ^8.5.0
    unocss-preset-scrollbar-hide: ^1.0.1
    vitest: ^3.2.3
  lint:
    '@antfu/eslint-config': ^4.13.2
    '@nuxt/eslint': ^1.4.1
    eslint: ^9.27.0
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
  prod:
    '@headlessui/vue': ^1.7.23
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': ^1.10.0
    '@unocss/nuxt': ^66.1.2
    '@vueuse/core': ^13.2.0
    '@vueuse/nuxt': ^13.2.0
    axios: ^1.9.0
    bullmq: ^5.54.3
    cheerio: ^1.0.0
    crypt3-md5: ^1.1.1
    date-fns: ^4.1.0
    dotenv: ^16.5.0
    drizzle-orm: ^0.43.1
    he: ^1.2.0
    http-cookie-agent: ^7.0.1
    iconv-lite: ^0.6.3
    ioredis: ^5.6.1
    lodash-es: ^4.17.21
    nuxt: ^3.17.4
    p-limit: ^6.2.0
    pg: ^8.16.0
    php-serialize: ^5.1.3
    progress-stream: ^2.0.0
    tough-cookie: ^5.1.2
    tsx: ^4.19.4
    ufo: ^1.6.1
    unocss: ^66.1.2
    vue: ^3.5.14
    vue-router: ^4.5.1
    xml2js: ^0.6.2
    zod: ^3.25.28
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract
  - sharp
  - simple-git-hooks
  - unrs-resolver
