packages:
  - 'packages/*'
  - 'apps/*'

catalogs:
  dev:
    '@antfu/nip': ^0.1.0
  lint:
    '@antfu/eslint-config': ^4.13.2
    eslint: ^9.27.0
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
