name: Deploy Monorepo

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kódu
      - uses: actions/checkout@v3

      - name: Create test.txt
        run: echo "abcd" > test.txt

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-ci

      # 6️⃣ Deploy na STAGING server
      - name: Deploy to staging server
        run: |
          scp -o StrictHostKeyChecking=no test.txt brojor@prod-01
